In [3]:
# Step1 - Importing necessary libraries 
# Step2 - Read csv file

import pandas as pd
import numpy as np

data = pd.read_csv(r"C:\Users\priya\Downloads\Predicting Manufacturing Defects.csv")
data


C:\Users\priya\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


ProductionVolume  ProductionCost  SupplierQuality  DefectRate  \
0                  202    13175.403780        86.648534    3.121492   
1                  535    19770.046090        86.310664    0.819531   
2                  960    19060.821000        82.132472    4.514504   
3                  370     5647.606037        87.335966    0.638524   
4                  206     7472.222236        81.989893    3.867784   
...                ...             ...              ...         ...   
3235               762    11325.689260        89.252385    2.667570   
3236               335     5598.837988        95.701437    0.751272   
3237               835    11736.177710        96.431554    4.899756   
3238               302    13664.196210        91.089782    4.057665   
3239               355    13563.605810        83.595956    2.705502   

      QualityScore  MaintenanceHours  AdditiveMaterialCost  DefectStatus  
0        63.463494                 9            236.439301             1  
1        83.697818                20            353.957631             1  
2        90.350550                 1            396.189402             1  
3        67.628690                 8            164.135870             1  
4        82.728334                 9            365.708964             1  
...            ...               ...                   ...           ...  
3235     87.141681                16            299.829577             0  
3236     95.562997                11            245.524560             0  
3237     77.973442                 0            206.490010             1  
3238     95.755591                 6            203.771655             0  
3239     94.630965                13            324.825754             0  

[3240 rows x 8 columns]

In [4]:
# pip install --upgrade scikit-learn joblib pandas numpy


In [5]:
pip install

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


ERROR: You must give at least one requirement to install (see "pip help install")


In [6]:
# Step3 - Check null values

data.isnull().sum()

ProductionVolume        0
ProductionCost          0
SupplierQuality         0
DefectRate              0
QualityScore            0
MaintenanceHours        0
AdditiveMaterialCost    0
DefectStatus            0
dtype: int64

In [7]:
# Step4 - checking if there is any categorical column/feature in our dataset if present,then convert it into numerical

data.info()  #we can see here is no categorical column is present in our dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3240 entries, 0 to 3239
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   ProductionVolume      3240 non-null   int64  
 1   ProductionCost        3240 non-null   float64
 2   SupplierQuality       3240 non-null   float64
 3   DefectRate            3240 non-null   float64
 4   QualityScore          3240 non-null   float64
 5   MaintenanceHours      3240 non-null   int64  
 6   AdditiveMaterialCost  3240 non-null   float64
 7   DefectStatus          3240 non-null   int64  
dtypes: float64(5), int64(3)
memory usage: 202.6 KB


In [8]:
# Step5 - Define input/output variables

din = data.drop(columns=['DefectStatus'])
dout = data['DefectStatus']

din.columns

Index(['ProductionVolume', 'ProductionCost', 'SupplierQuality', 'DefectRate',
       'QualityScore', 'MaintenanceHours', 'AdditiveMaterialCost'],
      dtype='object')

In [9]:
# Step 6 Data Splitting into training and testing datasets

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(din,dout,test_size=0.2,random_state=10)

print(data.shape)
x_train.shape,y_train.shape,x_test.shape,y_test.shape



(3240, 8)


((2592, 7), (2592,), (648, 7), (648,))

In [10]:
# Step7 fitting the training data into  model

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=20)
rf_model.fit(x_train,y_train)

RandomForestClassifier(n_estimators=20)

In [21]:
x_test.head(8)

ProductionVolume  ProductionCost  SupplierQuality  DefectRate  \
2840               614    13930.495550        83.278405    1.239186   
815                460     6672.683185        85.708081    1.264490   
2293               489    13104.491100        83.249968    2.807078   
2377               651    15134.943530        86.859330    4.315056   
237                918    18726.351030        96.213671    1.520917   
3114               566     8089.700538        86.267354    2.807314   
731                495     7143.139420        95.927814    2.195760   
837                985    12819.440710        88.222546    2.173113   

      QualityScore  MaintenanceHours  AdditiveMaterialCost  
2840     84.070578                17            176.137016  
815      61.698836                 4            417.787232  
2293     60.978588                 0            378.928643  
2377     98.583207                19            163.590499  
237      79.477629                10            267.968337  
3114     80.163805                15            119.996806  
731      77.811791                 7            408.406602  
837      70.869541                 4            341.676365

In [11]:
# Step 8 Predicting the model

y_pred = rf_model.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,

In [12]:
# Predicting a particular row 

y_pred1 = rf_model.predict(np.array([202,13175.403780,86.648534,3.121492,63.463494,9,236.439301]).reshape(1,-1)) # Reshaping the 1D array to a 2D array with 1 row and 16 columns
y_pred1


C:\Users\priya\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [23]:
y_pred2 = rf_model.predict(np.array([495,7143.139420,95.927814,2.195760,77.811791,7,408.406602]).reshape(1,-1)) # Reshaping the 1D array to a 2D array with 1 row and 16 columns
y_pred2

C:\Users\priya\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [13]:
# Step9 - Check the Accuracy of model

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

accuracy = accuracy_score(y_test,y_pred)*100
conf_matrix = confusion_matrix(y_test,y_pred)
clas_report = classification_report(y_test,y_pred)

print("Accuracy Score \n",accuracy,"\n\n")
print("Confusion Matrix \n",conf_matrix,"\n\n")
print("Classification Report \n",clas_report,"\n\n")


Accuracy Score 
 95.98765432098766 


Confusion Matrix 
 [[ 80  23]
 [  3 542]] 


Classification Report 
               precision    recall  f1-score   support

           0       0.96      0.78      0.86       103
           1       0.96      0.99      0.98       545

    accuracy                           0.96       648
   macro avg       0.96      0.89      0.92       648
weighted avg       0.96      0.96      0.96       648
 




In [14]:
# save the model 

import joblib
joblib.dump(rf_model,'Production Defect Status.pkl')

['Production Defect Status.pkl']